version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/caart
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
#  ApplicationStop:
#  BeforeInstall:
#  AfterInstall:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
#  ValidateService:
