## CaArt 백엔드 서비스 배포
name: Deploy to Amazon EC2

on:
  push:
    branches: 
      - 'develop'
      # - 'BE/deploy/setting'
    paths:
      - '**.java'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Copy application.yml
      run: |
        cd ./backend
        mkdir src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
  
    - name: Build with Gradle
      run: |
        cd ./backend
        chmod +x gradlew
        ./gradlew bootJar
      
    - name: Copy file to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        rm: true
        source: "backend/build/libs/*.jar"
        target: ${{ secrets.SERVER_TARGET_PATH }}
        strip_components: 3
        
    - name: Display structure of distributed files
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.SERVER_TARGET_PATH }}
          ls -alh
          
    - name: Run server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ./start.sh
